using Microsoft.EntityFrameworkCore;

namespace BankingProject
{
    public class BankContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; } = null!;
        public DbSet<Account> Accounts { get; set; } = null!;
        public DbSet<Transaction> Transactions { get; set; } = null!;
        public DbSet<ChequeBookRequest> ChequeBookRequests { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                "Server=BIGFIG;Database=FiggyBankDB;Trusted_Connection=True;TrustServerCertificate=True;"
            );
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Account primary key is entered manually, not generated by SQL Server
            modelBuilder.Entity<Account>()
                .Property(a => a.AccountNumber)
                .ValueGeneratedNever();

            // Account inheritance
            modelBuilder.Entity<Account>()
                .HasDiscriminator<string>("AccountClass")
                .HasValue<Savings>("Savings")
                .HasValue<Checking>("Checking");

            // Customer -> Accounts
            modelBuilder.Entity<Account>()
                .HasOne(a => a.Customer)
                .WithMany(c => c.Accounts)
                .HasForeignKey(a => a.CustomerID);

            // Account -> Transactions
            modelBuilder.Entity<Transaction>()
                .HasOne(t => t.Account)
                .WithMany(a => a.Transactions)
                .HasForeignKey(t => t.AccountNumber);

            // Account -> Cheque Book Requests
            modelBuilder.Entity<ChequeBookRequest>()
                .HasOne(r => r.Account)
                .WithMany(a => a.ChequeBookRequests)
                .HasForeignKey(r => r.AccountNumber);
        }
    }
}